name: Push actions
on: [push]
jobs:
  Push-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
      - uses: actions/checkout@v2
      
      - name: Copy files
        run: | 
          cp -u -f ${GITHUB_WORKSPACE}/src/lsc.js ${GITHUB_WORKSPACE}/docs/
          cp -u -f ${GITHUB_WORKSPACE}/LICENSE ${GITHUB_WORKSPACE}/WordPress/
          cp -u -f ${GITHUB_WORKSPACE}/src/lsc.js ${GITHUB_WORKSPACE}/WordPress/
    
      - name: Minify CSS/JS
        uses: nizarmah/auto-minify@v2.1.1
        
      - name: Finalize WordPress plugin
        run: |
          cd ${GITHUB_WORKSPACE}/WordPress
          rm -f lsc.zip
          zip -9 -D -T lsc.zip *
    
      - name: Commit modified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GitHub action: Push actions"
          branch: ${{ github.ref }}
