name: Push actions
on: [push]
jobs:
  Push-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      
      - name: Copy files
        run: | 
          cp -f ${GITHUB_WORKSPACE}/src/lsc.js ${GITHUB_WORKSPACE}/docs/
          cp -f ${GITHUB_WORKSPACE}/LICENSE ${GITHUB_WORKSPACE}/add-ons/WordPress/
          cp -f ${GITHUB_WORKSPACE}/src/lsc.js ${GITHUB_WORKSPACE}/add-ons/WordPress/
          cp -f ${GITHUB_WORKSPACE}/src/lsc.js ${GITHUB_WORKSPACE}/add-ons/browser-extension/chrome/js/
    
      - name: Minify CSS/JS
        uses: nizarmah/auto-minify@v2.1.1

      - name: Update files from external sources
        run: |
          wget -v -O ${GITHUB_WORKSPACE}/add-ons/browser-extension/chrome/js/html-i18n.min.js https://raw.githubusercontent.com/nd1012/HTML-i18n/main/src/html-i18n.min.js

      - name: Delete not required files
        run: | 
          rm -f ${GITHUB_WORKSPACE}/add-ons/browser-extension/chrome/js/*.min.js
        
      - name: Finalize WordPress plugin
        run: |
          cd ${GITHUB_WORKSPACE}/add-ons/WordPress
          rm -f lsc.zip
          zip -9 -D -T lsc.zip *
        
      - name: Finalize Chrominum browser extension
        run: |
          cd ${GITHUB_WORKSPACE}/add-ons/browser-extension/chrome/
          rm -f lsc-chrominum-extension.zip
          zip -9 -D -T lsc-chrominum-extension.zip *
    
      - name: Commit modified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GitHub action: Push actions"
          branch: ${{ github.ref }}
